name: Metrics
on:
  # Updated daily
  schedule: [{cron: "0 0 * * *"}]
  # Or manually
  workflow_dispatch:
  # Or when pushing to main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bnjam
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: yes
      - name: Labels
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: jupyternotebook
          plugin_languages_limit: 10
